name: inzultz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '3.22.0'

dependencies:
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.5.8
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  fluttertoast: ^8.2.5
  go_router: ^14.1.3
  intl_phone_field: ^3.2.0
  logging: ^1.2.0
  riverpod_annotation: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
